name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose -r
    - name: Run tests
      run: cargo test --verbose
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-build
        path: target/release/solar_getter

  # release:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download all workflow run artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: ~/
  #     - name: Debug
  #       run: pwd && ls && ls ~/
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: "latest"
  #         prerelease: false
  #         files: "*-build"
